#!/bin/sh
set -eu

SECRETS_FILE="${GLAVK_RUNTIME_SECRETS_FILE:-/app/data/runtime-secrets.env}"
ENV_AUTH_SECRET_KEY="${AUTH_SECRET_KEY-}"
ENV_CREDENTIAL_ENCRYPTION_KEY="${CREDENTIAL_ENCRYPTION_KEY-}"
ENV_TRANSPORT_PRIVATE_KEY_B64="${TRANSPORT_PRIVATE_KEY_B64-}"
mkdir -p "$(dirname "$SECRETS_FILE")"

if [ -s "$SECRETS_FILE" ]; then
    set -a
    . "$SECRETS_FILE"
    set +a
fi

[ -z "$ENV_AUTH_SECRET_KEY" ] || AUTH_SECRET_KEY="$ENV_AUTH_SECRET_KEY"
[ -z "$ENV_CREDENTIAL_ENCRYPTION_KEY" ] || CREDENTIAL_ENCRYPTION_KEY="$ENV_CREDENTIAL_ENCRYPTION_KEY"
[ -z "$ENV_TRANSPORT_PRIVATE_KEY_B64" ] || TRANSPORT_PRIVATE_KEY_B64="$ENV_TRANSPORT_PRIVATE_KEY_B64"
export AUTH_SECRET_KEY CREDENTIAL_ENCRYPTION_KEY TRANSPORT_PRIVATE_KEY_B64

umask 077
TEMP_SECRETS_FILE="${SECRETS_FILE}.tmp"
python -m app.runtime_secrets > "$TEMP_SECRETS_FILE"
mv "$TEMP_SECRETS_FILE" "$SECRETS_FILE"

set -a
. "$SECRETS_FILE"
set +a

exec "$@"
